### ISSUE TITLE
Cannot download the checkpoints : Permission Denied

### ISSUE THREAD

**Issue by Tortoise17** [baidu-research/Soccernet-features#5]
Dear Friends,

I am trying to download your provided link from sub-repository for the checkpoints from below link

` wget https://bj.bcebos.com/v1/acg-algo/PaddleVideo_application/basketball/checkpoints_basketball.tar.gz`

and

`wget https://bj.bcebos.com/v1/acg-algo/PaddleVideo_application/basketball/datasets.tar.gz`

but permissions denied. If you would be kind to provide the link active would be a great help.

Best greetings.

**Comment by paulxinzhou** [comment]
@Tortoise17 these are not necessary for this repo. You can skip wget-ting these.

**Comment by Tortoise17** [comment]
@paulxinzhou I was trying basketball stuff. If you can help to download would be great help as checkpoints for basketball cannot be downloaded

**Comment by Tortoise17** [comment]
@paulxinzhou OK got your point. Thank you.
